name: upgrader_example
description: Demonstrates how to use the upgrader package.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.1 <3.0.0'
  flutter: ">=3.0.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  upgrader:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter

  flutter_test:
    sdk: flutter

  test:

flutter:
  uses-material-design: true
